### ISSUE TITLE
Crear modelos de datos

### ISSUE THREAD

**Issue by pausm99** [pausm99/pomos-garden#42]
Definir los modelos de datos siguientes:
- User
- Task
- Sesión

**Comment by frmuller41182** [comment]
First iteration can be found here: https://dbdiagram.io/d/Pomo-Garden-669e865f8b4bb5230e05e914



![Image](https://github.com/user-attachments/assets/f75252b4-b9dc-4b74-a3a3-f4be2d932d75)

**Comment by frmuller41182** [comment]
With many to many relationship:



![Image](https://github.com/user-attachments/assets/a6d9dc16-f03b-4e06-890d-bf60b965602a)

**Comment by frmuller41182** [comment]
![Image](https://github.com/user-attachments/assets/85307815-cdec-40ae-bd79-86c50035b3ea)

LINK: https://dbdiagram.io/d/Pomo-Garden-669e865f8b4bb5230e05e914

-------------------------------------

Updates since last discussion:

1. Session Status is a boolean in_progress bool [default: false]
2. Added Tag table
3. Status of Task Entity is now an enum (backlog, in_progress, completed)
4. Added many to many relationship between Task and Tags. Task Table has a field tags with type being an Array of Task entity.
